create database p1;
use p1;

select * from customer limit 10;

-- CITY WISE PURCHASE TOTAL AMOUNT
DELIMITER //
CREATE PROCEDURE LOCATION_BASED_SALES(IN CITY VARCHAR(50))
BEGIN
	SELECT LOCATION,SUM(PURCHASE_AMOUNT) AS TOTAL_PURCHASE FROM CUSTOMER GROUP BY LOCATION HAVING LOCATION=CITY;
END //
DELIMITER ;


CALL LOCATION_BASED_SALES('Maine');
SELECT DISTINCT(LOCATION) FROM CUSTOMER;

-- MAXIMUM  PURCHASED CITY BASED ON AMOUNT
SELECT LOCATION,SUM(PURCHASE_AMOUNT) AS TOTAL_PURCHASED_AMOUNT FROM CUSTOMER 
GROUP BY LOCATION 
ORDER BY TOTAL_PURCHASED_AMOUNT DESC LIMIT 1;

-- SECOND MAXIMUM PURCHASED CITY BASED ON AMOUNT
SELECT LOCATION,SUM(PURCHASE_AMOUNT) AS TOTAL_PURCHASED_AMOUNT FROM CUSTOMER 
GROUP BY LOCATION 
ORDER BY TOTAL_PURCHASED_AMOUNT DESC LIMIT 1 OFFSET 1;

-- CATEGORY WISE SALES
DELIMITER //
CREATE PROCEDURE CATEGORY_SALES(IN CATEGORY VARCHAR(50))
BEGIN
	SELECT CATEGORY,SUM(PURCHASE_AMOUNT) AS TOTAL_PURCHASED_AMOUNT FROM CUSTOMER GROUP BY CATEGORY HAVING CATEGORY=CATEGORY;
END //
DELIMITER ;

CALL CATEGORY_SALES('Clothing');
CALL CATEGORY_SALES('Accessories');
CALL CATEGORY_SALES('Footwear');
CALL CATEGORY_SALES('Outerwear');

-- MAXIMUM PAUCHASED CATEGORY BASED ON AMOUNT
SELECT CATEGORY,SUM(PURCHASE_AMOUNT) AS TOTAL_PURCHASED_AMOUNT FROM CUSTOMER GROUP BY CATEGORY ORDER BY TOTAL_PURCHASED_AMOUNT DESC LIMIT 1;

-- WHERE CLAUSE
SELECT CUSTOMER_ID,AGE,PURCHASE_AMOUNT FROM CUSTOMER WHERE PURCHASE_AMOUNT>50;

-- NO OF ITEMS PURCHASED BASED ON CATEGORIES
SELECT CATEGORY,COUNT(ITEM_PURCHASED) AS ITEM_PURCHASED FROM CUSTOMER
GROUP BY CATEGORY
ORDER BY ITEM_PURCHASED DESC;

-- AVG OF SALES BASED ON CATEGORY
SELECT CATEGORY,AVG(PURCHASE_AMOUNT) AS AVG_PURCHASE_AMOUNT FROM CUSTOMER
GROUP BY CATEGORY
ORDER BY AVG_PURCHASE_AMOUNT DESC;


 




 

